apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  labels:
{{ include "gospel-installer.labels" . | indent 4 }}
data:
  nginx.conf: |


    map $sent_http_content_type $expires {
      default			30d;
      application/json	off;
      application/javascript	7d;
    }

    server {
      listen       80 default_server;
      listen     443 ssl default_server;

      ssl_certificate      certs/https1.cert;
      ssl_certificate_key  certs/https1.key;
      ssl_protocols TLSv1.2 TLSv1.3;# Requires nginx >= 1.13.0 else use TLSv1.2
      ssl_prefer_server_ciphers on;
      ssl_ciphers ECDH+AESGCM:ECDH+CHACHA20:ECDH+AES256:ECDH+AES128:!aNULL:!SHA1;
      ssl_dhparam /etc/nginx/dhparam.pem; # openssl dhparam -out /etc/nginx/dhparam.pem 4096
      ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
      ssl_session_timeout  10m;
      server_name  $HOST;

      gzip on;
      gzip_disable "msie6";

      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

      access_log stderr main;
      error_log stderr;

      location / {
        root   /var/www/installer/;
        index  index.html;
        try_files $uri $uri/ /index.html;
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' 'https://$host';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Vary' 'Origin';
          add_header "Content-Security-Policy" "default-src https://$host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://chart.googleapis.com/ https://www.gstatic.com/charts/ https://fonts.googleapis.com; img-src 'self' data: https://chart.googleapis.com/; style-src 'self' 'unsafe-inline' https://www.gstatic.com/charts/ https://fonts.googleapis.com; connect-src 'self' data: wss://$host https://docs.gospel.tech; font-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com/; worker-src 'self' blob:";
          add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain charset=UTF-8';
          add_header 'Content-Length' 0;
          return 204;
        }
        add_header 'Access-Control-Allow-Origin' 'https://$host';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
        add_header 'Vary' 'Origin';
        add_header "Content-Security-Policy" "default-src https://$host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://chart.googleapis.com/ https://www.gstatic.com/charts/ https://fonts.googleapis.com; img-src 'self' data: https://chart.googleapis.com/; style-src 'self' 'unsafe-inline' https://www.gstatic.com/charts/ https://fonts.googleapis.com; connect-src 'self' data: wss://$host https://docs.gospel.tech; font-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com/; worker-src 'self' blob:";
        add_header "X-XSS-Protection" "1; mode=block";
        add_header "X-Content-Type-Options" "nosniff";
        add_header "X-Frame-Options" "DENY";
        expires $expires;
      }

      location ^~ /api/ {
        proxy_pass_request_headers on;
        proxy_pass_request_body on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:8080/;
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' 'https://$host';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Vary' 'Origin';
          add_header "Content-Security-Policy" "default-src https://$host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://chart.googleapis.com/ https://www.gstatic.com/charts/ https://fonts.googleapis.com; img-src 'self' data: https://chart.googleapis.com/; style-src 'self' 'unsafe-inline' https://www.gstatic.com/charts/ https://fonts.googleapis.com; connect-src 'self' data: wss://$host https://docs.gospel.tech; font-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com/";
          add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain charset=UTF-8';
          add_header 'Content-Length' 0;
          add_header "X-XSS-Protection" "1; mode=block";
          add_header "X-Content-Type-Options" "nosniff";
          add_header "X-Frame-Options" "DENY";
          return 204;
        }
        if ($request_method = 'POST') {
          add_header 'Access-Control-Allow-Origin' 'https://$host';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Vary' 'Origin';
          add_header "Content-Security-Policy" "default-src https://$host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://chart.googleapis.com/ https://www.gstatic.com/charts/ https://fonts.googleapis.com; img-src 'self' data: https://chart.googleapis.com/; style-src 'self' 'unsafe-inline' https://www.gstatic.com/charts/ https://fonts.googleapis.com; connect-src 'self' data: wss://$host https://docs.gospel.tech; font-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com/";
          add_header "X-XSS-Protection" "1; mode=block";
          add_header "X-Content-Type-Options" "nosniff";
          add_header "X-Frame-Options" "DENY";
        }
        if ($request_method = 'GET') {
          add_header 'Access-Control-Allow-Origin' 'https://$host';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization';
          add_header 'Vary' 'Origin';
          add_header "Content-Security-Policy" "default-src https://$host; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://chart.googleapis.com/ https://www.gstatic.com/charts/ https://fonts.googleapis.com; img-src 'self' data: https://chart.googleapis.com/; style-src 'self' 'unsafe-inline' https://www.gstatic.com/charts/ https://fonts.googleapis.com; connect-src 'self' data: wss://$host https://docs.gospel.tech; font-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com/";
          add_header "X-XSS-Protection" "1; mode=block";
          add_header "X-Content-Type-Options" "nosniff";
          add_header "X-Frame-Options" "DENY";
        }
      }
    }