---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gcp-installer-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-installer
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gcp-installer-binding
subjects:
  - kind: ServiceAccount
    name: gcp-installer-service-account
roleRef:
  kind: Role
  name: gcp-installer
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    io.kompose.service: gospel-installer-pod
  name: gospel-installer-pod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: gospel-installer-pod
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gospel-installer-pod
    spec:
      containers:
      - env:
        image: gospel-docker-local.jfrog.io/installer-ui:5
        imagePullPolicy: Always
        name: gospel-installer-frontend
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gospel-docker-local.jfrog.io/k8s-installer:9
        imagePullPolicy: Always
        name: gospel-installer-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gospel-artifactory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: my-service-account
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  labels:
    io.kompose.service: gospel-installer-pod
  name: installer-frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: installer-frontend
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    io.kompose.service: gospel-installer-pod
  sessionAffinity: None
  type: LoadBalancer
---
kind: Secret
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2dvc3BlbC1kb2NrZXItbG9jYWwuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJnb3NwZWwtZGV2Y2xvdWQtMSIsInBhc3N3b3JkIjoianV3Y293LTNoeXJ4aS1ueVd2YWgiLCJlbWFpbCI6ImVsbGlvdHQud2hpdGluZ0Bnb3NwZWwudGVjaCIsImF1dGgiOiJaMjl6Y0dWc0xXUmxkbU5zYjNWa0xURTZhblYzWTI5M0xUTm9lWEo0YVMxdWVWZDJZV2c9In19fQ==
metadata:
  name: gospel-artifactory
type: kubernetes.io/dockerconfigjson
