applicationApiVersion: v1beta1
properties:
  name:
    type: string
    default: gospel-installer
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: gospel
    x-google-marketplace:
      type: NAMESPACE
  controller.serviceAccount:
    type: string
    title: Gospel Installer Service Account
    description: Service account to assign to Gospel Installer
    default: gospel-installer-service-account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: cluster-admin
    frontend.image:
      type: string
      default: "$REGISTRY/gospel-installer-frontend:$TAG"
      x-google-marketplace:
        type: IMAGE
    backend.image:
      type: string
      default: "$REGISTRY/gospel-installer-backend:$TAG"
      x-google-marketplace:
        type: IMAGE
required:
  - name
  - namespace