applicationApiVersion: v1beta1
properties:
  name:
    type: string
    default: gospel-technologies-gcp
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: gospel
    x-google-marketplace:
      type: NAMESPACE
  controller.serviceAccount:
    type: string
    title: Gospel Installer Service Account
    description: Service account to assign to Gospel Installer
    default: gospel-installer-service-account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: cluster-admin
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
  publicIp.available:
    type: boolean
    default: false
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  frontend.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp:4.5
    x-google-marketplace:
      type: IMAGE
  backend.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/gospel-installer-backend:4.5
    x-google-marketplace:
      type: IMAGE
  chaincode.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/chaincode:4.5.45
    x-google-marketplace:
      type: IMAGE
  dataimporter.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/dataimporter:4.5
    x-google-marketplace:
      type: IMAGE
  endorsing-peer.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/endorsing-peer:4.5
    x-google-marketplace:
      type: IMAGE
  gospel-backend.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/gospel-backend:4.5
    x-google-marketplace:
      type: IMAGE
  keystore.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/keystore:4.5
    x-google-marketplace:
      type: IMAGE
  nginx.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/nginx:4.5
    x-google-marketplace:
      type: IMAGE
  orchestrator.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/ca-orchestrator:4.5
    x-google-marketplace:
      type: IMAGE
  orderer.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/orderer:4.5
    x-google-marketplace:
      type: IMAGE
  signer.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/ca-signer:4.5
    x-google-marketplace:
      type: IMAGE
  soas.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/ca-soas:4.5
    x-google-marketplace:
      type: IMAGE
  soau.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/ca-soau:4.5
    x-google-marketplace:
      type: IMAGE
  soi.image:
    type: string
    default: gcr.io/gospel-technology-public/gospel-technologies-gcp/ca-soi:4.5
    x-google-marketplace:
      type: IMAGE
required:
  - name
  - namespace
