applicationApiVersion: v1beta1
properties:
  name:
    type: string
    default: gospel-technology
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: gospel
    x-google-marketplace:
      type: NAMESPACE
  controller.serviceAccount:
    type: string
    title: Gospel Installer Service Account
    description: Service account to assign to Gospel Installer
    default: gospel-technology-service-account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: cluster-admin
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
  publicIp.available:
    type: boolean
    default: false
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  frontend.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  backend.image:
    type: string
    default: $REGISTRY/gospel-installer-backend:$TAG
    x-google-marketplace:
      type: IMAGE
  chaincode.image:
    type: string
    default: $REGISTRY/chaincode:$TAG
    x-google-marketplace:
      type: IMAGE
  dataImporter.image:
    type: string
    default: $REGISTRY/dataimporter:$TAG
    x-google-marketplace:
      type: IMAGE
  endorsingPeer.image:
    type: string
    default: $REGISTRY/endorsing-peer:$TAG
    x-google-marketplace:
      type: IMAGE
  gospelBackend.image:
    type: string
    default: $REGISTRY/gospel-backend:$TAG
    x-google-marketplace:
      type: IMAGE
  keystore.image:
    type: string
    default: $REGISTRY/keystore:$TAG
    x-google-marketplace:
      type: IMAGE
  nginx.image:
    type: string
    default: $REGISTRY/nginx:$TAG
    x-google-marketplace:
      type: IMAGE
  orchestrator.image:
    type: string
    default: $REGISTRY/ca-orchestrator:$TAG
    x-google-marketplace:
      type: IMAGE
  orderer.image:
    type: string
    default: $REGISTRY/orderer:$TAG
    x-google-marketplace:
      type: IMAGE
  signer.image:
    type: string
    default: $REGISTRY/ca-signer:$TAG
    x-google-marketplace:
      type: IMAGE
  soas.image:
    type: string
    default: $REGISTRY/ca-soas:$TAG
    x-google-marketplace:
      type: IMAGE
  soau.image:
    type: string
    default: $REGISTRY/ca-soau:$TAG
    x-google-marketplace:
      type: IMAGE
  soi.image:
    type: string
    default: $REGISTRY/ca-soi:$TAG
    x-google-marketplace:
      type: IMAGE
required:
  - name
  - namespace
