apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gospel-technology.fullname" . }}
  labels:
{{ include "gospel-technology.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "gospel-technology.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "gospel-technology.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: Always
          ports:
            - name: frontend-http
              containerPort: 80
              protocol: TCP
            - name: frontend-https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: Always
          ports:
            - name: installer-back
              containerPort: 8080
              protocol: TCP
          env:
          - name: APP_K8S_NAME
            value: {{ include "gospel-technology.name" . }}
          - name: APP_K8S_INSTANCE
            value: {{ .Release.Name }}
          - name: NAMESPACE
            value: {{.Release.Namespace}}
      serviceAccountName: {{ .Values.controller.serviceAccount }}
      volumes:
        - name: certs
          secret:
            secretName: {{.Release.Name}}-frontend-secret
        - name: nginx-config
          configMap:
            name: {{.Release.Name}}-frontend-configmap
