apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-frontend-secret
  labels:
{{ include "gospel-technology.labels" . | indent 4 }}
data:
{{- if .Values.tls.base64EncodedCertificate }}
  https1.cert: |
{{ .Values.tls.base64EncodedCertificate | indent 4 }}
{{- end }}
{{- if .Values.tls.base64EncodedPrivateKey }}
  https1.key: |
{{ .Values.tls.base64EncodedPrivateKey | indent 4 }}
{{- end }}
