apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gospel-installer
data:
  https1.cert: |
{{ .Values.tls.base64EncodedCertificate | indent 4 }}
  https1.key: |
{{ .Values.tls.base64EncodedPrivateKey | indent 4 }}
