apiVersion: v1
kind: Service
metadata:
  name: {{ include "gospel-technology.fullname" . }}
  labels:
{{ include "gospel-technology.labels" . | indent 4 }}
spec:
  ports:
    - name: {{.Chart.Name}}-frontend-http
      port: {{ .Values.frontendService.httpPort }}
      targetPort: 80
      protocol: TCP
    - name: {{.Chart.Name}}-frontend-https
      port: {{ .Values.frontendService.httpsPort }}
      targetPort: 443
      protocol: TCP
  selector:
{{ include "gospel-technology.labels" . | indent 4 }}
  {{ if .Values.publicIp.available }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
